apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: graceful
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: mateuszdyminski/app-container-graceful:v1
        imagePullPolicy: Always
        env:
        - name: APP_DB_HOST
          value: "mysql.mysql"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: graceful
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
      protocol: TCP
  selector:
    app: app